-- ============================================================================
-- Korgo Pro — Clôtures mensuelles de trésorerie (ventes du mois)
--
-- Chaque fin de mois, on « ferme » le compte des ventes : un enregistrement
-- fige les totaux du mois (ventes, encaissé, crédit, dépenses, net) et le
-- solde de chaque compte de trésorerie à la date de clôture.
--
-- À exécuter une fois sur le projet Supabase (SQL Editor) — idempotent.
-- ============================================================================

create table if not exists public.monthly_closures (
    id              bigint generated by default as identity primary key,
    period          varchar(7)  not null unique,          -- 'YYYY-MM'
    sales_count     integer     not null default 0,
    total_sales     double precision not null default 0, -- somme total_amount
    total_collected double precision not null default 0, -- somme (amount_paid - change_amount)
    total_credit    double precision not null default 0, -- restant dû clients
    total_out       double precision not null default 0, -- dépenses (mouvements OUT)
    net             double precision not null default 0, -- encaissé - dépenses
    balances        jsonb       not null default '[]',   -- snapshot des comptes à la clôture
    status          varchar(20) not null default 'OPEN', -- OPEN / CLOSED
    closed_by       integer     references public.users(id),
    closed_at       timestamptz,
    notes           text,
    created_at      timestamptz not null default now()
);

create index if not exists idx_monthly_closures_period on public.monthly_closures (period desc);

-- RLS : lecture pour tout utilisateur authentifié, écriture ADMIN uniquement
-- (même modèle que les autres tables métier).
alter table public.monthly_closures enable row level security;

drop policy if exists "mc_select_all" on public.monthly_closures;
create policy "mc_select_all" on public.monthly_closures
    for select to authenticated
    using (true);

drop policy if exists "mc_write_admin" on public.monthly_closures;
create policy "mc_write_admin" on public.monthly_closures
    for all to authenticated
    using (app_security.is_admin())
    with check (app_security.is_admin());
