"""Add currency field to Sale

Revision ID: 92a3de20ce0e
Revises: ed15b98aa383
Create Date: 2026-01-12 12:29:27.860129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92a3de20ce0e'
down_revision: Union[str, Sequence[str], None] = 'ed15b98aa383'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sale_returns', 'currency')
    op.add_column('sales', sa.Column('currency', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'currency')
    op.add_column('sale_returns', sa.Column('currency', sa.VARCHAR(length=10), nullable=True))
    # ### end Alembic commands ###
