"""ajout champs note verss notes

Revision ID: d4cb3dc41905
Revises: d92bd2ad085e
Create Date: 2026-01-18 01:01:01.212594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4cb3dc41905'
down_revision: Union[str, Sequence[str], None] = 'd92bd2ad085e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('notes', sa.Text(), nullable=True))
    op.drop_column('suppliers', 'note')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('note', sa.TEXT(), nullable=True))
    op.drop_column('suppliers', 'notes')
    # ### end Alembic commands ###
